name: Build Windows App (PRO)

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore BRDesktopAssistant_Pro.csproj

      - name: Publish (self-contained single exe)
        run: |
          dotnet publish BRDesktopAssistant_Pro.csproj `
            -c Release `
            -r win-x64 `
            --self-contained true `
            -p:PublishSingleFile=true `
            -p:IncludeNativeLibrariesForSelfExtract=true `
            -p:DebugType=None `
            -p:DebugSymbols=false

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BRDesktopAssistant-PRO-win-x64
          path: bin/Release/net8.0-windows/win-x64/publish/**
